# Generated by Django 5.1 on 2025-02-26 14:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_remove_tenant_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Prefer not to say')], default='U', max_length=1, verbose_name='Gender')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('medical_history', models.TextField(blank=True, verbose_name='Medical History')),
                ('allergies', models.TextField(blank=True, verbose_name='Allergies')),
                ('current_medications', models.TextField(blank=True, verbose_name='Current Medications')),
                ('insurance_id', models.CharField(blank=True, max_length=50, verbose_name='Insurance ID')),
                ('last_dental_visit', models.DateField(blank=True, null=True, verbose_name='Last Dental Visit')),
                ('dental_insurance', models.CharField(blank=True, max_length=100, verbose_name='Dental Insurance Provider')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='patient_profiles/', verbose_name='Profile Picture')),
                ('primary_dentist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_patients', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='patients_pa_last_na_1b32a7_idx'), models.Index(fields=['date_of_birth'], name='patients_pa_date_of_4302f5_idx')],
                'unique_together': {('first_name', 'last_name', 'date_of_birth', 'tenant')},
            },
        ),
    ]
