# Generated by Django 5.1 on 2025-03-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_dentist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_picture',
            field=models.URLField(blank=True, null=True, verbose_name='Profile Picture URL'),
        ),
    ]
