# Generated by Django 5.1 on 2025-02-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='paid_until',
            field=models.DateField(null=True),
        ),
    ]
