# Generated by Django 5.1 on 2025-02-13 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_paid_until'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clinic',
        ),
    ]
