# Generated by Django 5.1 on 2025-02-22 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_delete_clinic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='user',
        ),
    ]
