# Generated by Django 5.1 on 2025-04-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedure',
            old_name='provider',
            new_name='dentist',
        ),
        migrations.AlterField(
            model_name='procedure',
            name='procedure_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date and time the procedure is planned, scheduled, or was completed.', null=True),
        ),
    ]
