# Generated by Django 5.1 on 2025-04-26 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_rename_provider_procedure_dentist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='dentist',
            field=models.ForeignKey(blank=True, help_text='The dentist who performed or is scheduled to perform the procedure.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_procedures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual price charged for this specific procedure instance.', max_digits=10, null=True),
        ),
    ]
