# Generated by Django 5.1 on 2025-03-03 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('tenants', '0004_remove_tenant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
    ]
