# Generated by Django 5.1 on 2025-04-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
