# Generated by Django 5.1 on 2025-04-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_expires_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='expires_at',
            new_name='expiry_date',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='selling_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='cost_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
