# Generated by Django 5.1 on 2025-04-24 21:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('universal_number', models.CharField(blank=True, help_text='Universal Numbering System (e.g., 1-32 for permanent, A-T for primary)', max_length=3, null=True, unique=True)),
                ('fdi_number', models.CharField(help_text='FDI World Dental Federation notation (e.g., 11-48 for permanent, 51-85 for primary)', max_length=2, unique=True)),
                ('palmer_notation', models.CharField(blank=True, help_text='Palmer notation symbol (e.g., ┘1, └8)', max_length=5, null=True)),
                ('name', models.CharField(blank=True, help_text='Common name (e.g., Upper Right Third Molar)', max_length=100, null=True)),
                ('arch', models.CharField(blank=True, choices=[('MAX', 'Maxillary (Upper)'), ('MAN', 'Mandibular (Lower)')], max_length=3, null=True)),
                ('quadrant', models.CharField(blank=True, choices=[('UR', 'Upper Right'), ('UL', 'Upper Left'), ('LR', 'Lower Right'), ('LL', 'Lower Left')], max_length=2, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Is this a primary (deciduous/baby) tooth?')),
            ],
            options={
                'verbose_name': 'Tooth',
                'verbose_name_plural': 'Teeth',
                'ordering': ['fdi_number'],
            },
        ),
    ]
