# Generated by Django 5.1 on 2025-04-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tooth',
            name='name',
        ),
        migrations.AddField(
            model_name='tooth',
            name='name_en',
            field=models.CharField(blank=True, help_text='Common name in English', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tooth',
            name='name_fr',
            field=models.CharField(blank=True, help_text='Common name in French', max_length=100, null=True),
        ),
    ]
