# Generated by Django 5.1 on 2025-04-25 14:38

from django.db import migrations
from tooth.models import Tooth

# Define the standard tooth data (Permanent + Primary)
# Source: Combination of standard charts, requires verification for exact French terms if critical
TOOTH_DATA = [
    # Permanent Teeth (FDI: 11-18, 21-28, 31-38, 41-48 | Univ: 1-32)
    {'fdi': '18', 'univ': '1', 'palmer': '┘8', 'arch': 'MAX', 'quad': 'UR', 'primary': False, 'en': 'Upper Right Third Molar', 'fr': 'Troisième Molaire Supérieure Droite'},
    {'fdi': '17', 'univ': '2', 'palmer': '┘7', 'arch': 'MAX', 'quad': 'UR', 'primary': False, 'en': 'Upper Right Second Molar', 'fr': 'Deuxième Molaire Supérieure Droite'},
    {'fdi': '16', 'univ': '3', 'palmer': '┘6', 'arch': 'MAX', 'quad': 'UR', 'primary': False, 'en': 'Upper Right First Molar', 'fr': 'Première Molaire Supérieure Droite'},
    {'fdi': '15', 'univ': '4', 'palmer': '┘5', 'arch': 'MAX', 'quad': 'UR', 'primary': False, 'en': 'Upper Right Second Premolar', 'fr': 'Deuxième Prémolaire Supérieure Droite'},
    {'fdi': '14', 'univ': '5', 'palmer': '┘4', 'arch': 'MAX', 'quad': 'UR', 'primary': False, 'en': 'Upper Right First Premolar', 'fr': 'Première Prémolaire Supérieure Droite'},
    {'fdi': '13', 'univ': '6', 'palmer': '┘3', 'arch': 'MAX', 'quad': 'UR', 'primary': False, 'en': 'Upper Right Canine', 'fr': 'Canine Supérieure Droite'},
    {'fdi': '12', 'univ': '7', 'palmer': '┘2', 'arch': 'MAX', 'quad': 'UR', 'primary': False, 'en': 'Upper Right Lateral Incisor', 'fr': 'Incisive Latérale Supérieure Droite'},
    {'fdi': '11', 'univ': '8', 'palmer': '┘1', 'arch': 'MAX', 'quad': 'UR', 'primary': False, 'en': 'Upper Right Central Incisor', 'fr': 'Incisive Centrale Supérieure Droite'},

    {'fdi': '21', 'univ': '9', 'palmer': '└1', 'arch': 'MAX', 'quad': 'UL', 'primary': False, 'en': 'Upper Left Central Incisor', 'fr': 'Incisive Centrale Supérieure Gauche'},
    {'fdi': '22', 'univ': '10', 'palmer': '└2', 'arch': 'MAX', 'quad': 'UL', 'primary': False, 'en': 'Upper Left Lateral Incisor', 'fr': 'Incisive Latérale Supérieure Gauche'},
    {'fdi': '23', 'univ': '11', 'palmer': '└3', 'arch': 'MAX', 'quad': 'UL', 'primary': False, 'en': 'Upper Left Canine', 'fr': 'Canine Supérieure Gauche'},
    {'fdi': '24', 'univ': '12', 'palmer': '└4', 'arch': 'MAX', 'quad': 'UL', 'primary': False, 'en': 'Upper Left First Premolar', 'fr': 'Première Prémolaire Supérieure Gauche'},
    {'fdi': '25', 'univ': '13', 'palmer': '└5', 'arch': 'MAX', 'quad': 'UL', 'primary': False, 'en': 'Upper Left Second Premolar', 'fr': 'Deuxième Prémolaire Supérieure Gauche'},
    {'fdi': '26', 'univ': '14', 'palmer': '└6', 'arch': 'MAX', 'quad': 'UL', 'primary': False, 'en': 'Upper Left First Molar', 'fr': 'Première Molaire Supérieure Gauche'},
    {'fdi': '27', 'univ': '15', 'palmer': '└7', 'arch': 'MAX', 'quad': 'UL', 'primary': False, 'en': 'Upper Left Second Molar', 'fr': 'Deuxième Molaire Supérieure Gauche'},
    {'fdi': '28', 'univ': '16', 'palmer': '└8', 'arch': 'MAX', 'quad': 'UL', 'primary': False, 'en': 'Upper Left Third Molar', 'fr': 'Troisième Molaire Supérieure Gauche'},

    {'fdi': '38', 'univ': '17', 'palmer': '┐8', 'arch': 'MAN', 'quad': 'LL', 'primary': False, 'en': 'Lower Left Third Molar', 'fr': 'Troisième Molaire Inférieure Gauche'},
    {'fdi': '37', 'univ': '18', 'palmer': '┐7', 'arch': 'MAN', 'quad': 'LL', 'primary': False, 'en': 'Lower Left Second Molar', 'fr': 'Deuxième Molaire Inférieure Gauche'},
    {'fdi': '36', 'univ': '19', 'palmer': '┐6', 'arch': 'MAN', 'quad': 'LL', 'primary': False, 'en': 'Lower Left First Molar', 'fr': 'Première Molaire Inférieure Gauche'},
    {'fdi': '35', 'univ': '20', 'palmer': '┐5', 'arch': 'MAN', 'quad': 'LL', 'primary': False, 'en': 'Lower Left Second Premolar', 'fr': 'Deuxième Prémolaire Inférieure Gauche'},
    {'fdi': '34', 'univ': '21', 'palmer': '┐4', 'arch': 'MAN', 'quad': 'LL', 'primary': False, 'en': 'Lower Left First Premolar', 'fr': 'Première Prémolaire Inférieure Gauche'},
    {'fdi': '33', 'univ': '22', 'palmer': '┐3', 'arch': 'MAN', 'quad': 'LL', 'primary': False, 'en': 'Lower Left Canine', 'fr': 'Canine Inférieure Gauche'},
    {'fdi': '32', 'univ': '23', 'palmer': '┐2', 'arch': 'MAN', 'quad': 'LL', 'primary': False, 'en': 'Lower Left Lateral Incisor', 'fr': 'Incisive Latérale Inférieure Gauche'},
    {'fdi': '31', 'univ': '24', 'palmer': '┐1', 'arch': 'MAN', 'quad': 'LL', 'primary': False, 'en': 'Lower Left Central Incisor', 'fr': 'Incisive Centrale Inférieure Gauche'},

    {'fdi': '41', 'univ': '25', 'palmer': '┌1', 'arch': 'MAN', 'quad': 'LR', 'primary': False, 'en': 'Lower Right Central Incisor', 'fr': 'Incisive Centrale Inférieure Droite'},
    {'fdi': '42', 'univ': '26', 'palmer': '┌2', 'arch': 'MAN', 'quad': 'LR', 'primary': False, 'en': 'Lower Right Lateral Incisor', 'fr': 'Incisive Latérale Inférieure Droite'},
    {'fdi': '43', 'univ': '27', 'palmer': '┌3', 'arch': 'MAN', 'quad': 'LR', 'primary': False, 'en': 'Lower Right Canine', 'fr': 'Canine Inférieure Droite'},
    {'fdi': '44', 'univ': '28', 'palmer': '┌4', 'arch': 'MAN', 'quad': 'LR', 'primary': False, 'en': 'Lower Right First Premolar', 'fr': 'Première Prémolaire Inférieure Droite'},
    {'fdi': '45', 'univ': '29', 'palmer': '┌5', 'arch': 'MAN', 'quad': 'LR', 'primary': False, 'en': 'Lower Right Second Premolar', 'fr': 'Deuxième Prémolaire Inférieure Droite'},
    {'fdi': '46', 'univ': '30', 'palmer': '┌6', 'arch': 'MAN', 'quad': 'LR', 'primary': False, 'en': 'Lower Right First Molar', 'fr': 'Première Molaire Inférieure Droite'},
    {'fdi': '47', 'univ': '31', 'palmer': '┌7', 'arch': 'MAN', 'quad': 'LR', 'primary': False, 'en': 'Lower Right Second Molar', 'fr': 'Deuxième Molaire Inférieure Droite'},
    {'fdi': '48', 'univ': '32', 'palmer': '┌8', 'arch': 'MAN', 'quad': 'LR', 'primary': False, 'en': 'Lower Right Third Molar', 'fr': 'Troisième Molaire Inférieure Droite'},

    # Primary Teeth (FDI: 51-55, 61-65, 71-75, 81-85 | Univ: A-T)
    {'fdi': '55', 'univ': 'A', 'palmer': None, 'arch': 'MAX', 'quad': 'UR', 'primary': True, 'en': 'Upper Right Second Primary Molar', 'fr': 'Deuxième Molaire Primaire Supérieure Droite'},
    {'fdi': '54', 'univ': 'B', 'palmer': None, 'arch': 'MAX', 'quad': 'UR', 'primary': True, 'en': 'Upper Right First Primary Molar', 'fr': 'Première Molaire Primaire Supérieure Droite'},
    {'fdi': '53', 'univ': 'C', 'palmer': None, 'arch': 'MAX', 'quad': 'UR', 'primary': True, 'en': 'Upper Right Primary Canine', 'fr': 'Canine Primaire Supérieure Droite'},
    {'fdi': '52', 'univ': 'D', 'palmer': None, 'arch': 'MAX', 'quad': 'UR', 'primary': True, 'en': 'Upper Right Primary Lateral Incisor', 'fr': 'Incisive Latérale Primaire Supérieure Droite'},
    {'fdi': '51', 'univ': 'E', 'palmer': None, 'arch': 'MAX', 'quad': 'UR', 'primary': True, 'en': 'Upper Right Primary Central Incisor', 'fr': 'Incisive Centrale Primaire Supérieure Droite'},

    {'fdi': '61', 'univ': 'F', 'palmer': None, 'arch': 'MAX', 'quad': 'UL', 'primary': True, 'en': 'Upper Left Primary Central Incisor', 'fr': 'Incisive Centrale Primaire Supérieure Gauche'},
    {'fdi': '62', 'univ': 'G', 'palmer': None, 'arch': 'MAX', 'quad': 'UL', 'primary': True, 'en': 'Upper Left Primary Lateral Incisor', 'fr': 'Incisive Latérale Primaire Supérieure Gauche'},
    {'fdi': '63', 'univ': 'H', 'palmer': None, 'arch': 'MAX', 'quad': 'UL', 'primary': True, 'en': 'Upper Left Primary Canine', 'fr': 'Canine Primaire Supérieure Gauche'},
    {'fdi': '64', 'univ': 'I', 'palmer': None, 'arch': 'MAX', 'quad': 'UL', 'primary': True, 'en': 'Upper Left First Primary Molar', 'fr': 'Première Molaire Primaire Supérieure Gauche'},
    {'fdi': '65', 'univ': 'J', 'palmer': None, 'arch': 'MAX', 'quad': 'UL', 'primary': True, 'en': 'Upper Left Second Primary Molar', 'fr': 'Deuxième Molaire Primaire Supérieure Gauche'},

    {'fdi': '75', 'univ': 'K', 'palmer': None, 'arch': 'MAN', 'quad': 'LL', 'primary': True, 'en': 'Lower Left Second Primary Molar', 'fr': 'Deuxième Molaire Primaire Inférieure Gauche'},
    {'fdi': '74', 'univ': 'L', 'palmer': None, 'arch': 'MAN', 'quad': 'LL', 'primary': True, 'en': 'Lower Left First Primary Molar', 'fr': 'Première Molaire Primaire Inférieure Gauche'},
    {'fdi': '73', 'univ': 'M', 'palmer': None, 'arch': 'MAN', 'quad': 'LL', 'primary': True, 'en': 'Lower Left Primary Canine', 'fr': 'Canine Primaire Inférieure Gauche'},
    {'fdi': '72', 'univ': 'N', 'palmer': None, 'arch': 'MAN', 'quad': 'LL', 'primary': True, 'en': 'Lower Left Primary Lateral Incisor', 'fr': 'Incisive Latérale Primaire Inférieure Gauche'},
    {'fdi': '71', 'univ': 'O', 'palmer': None, 'arch': 'MAN', 'quad': 'LL', 'primary': True, 'en': 'Lower Left Primary Central Incisor', 'fr': 'Incisive Centrale Primaire Inférieure Gauche'},

    {'fdi': '81', 'univ': 'P', 'palmer': None, 'arch': 'MAN', 'quad': 'LR', 'primary': True, 'en': 'Lower Right Primary Central Incisor', 'fr': 'Incisive Centrale Primaire Inférieure Droite'},
    {'fdi': '82', 'univ': 'Q', 'palmer': None, 'arch': 'MAN', 'quad': 'LR', 'primary': True, 'en': 'Lower Right Primary Lateral Incisor', 'fr': 'Incisive Latérale Primaire Inférieure Droite'},
    {'fdi': '83', 'univ': 'R', 'palmer': None, 'arch': 'MAN', 'quad': 'LR', 'primary': True, 'en': 'Lower Right Primary Canine', 'fr': 'Canine Primaire Inférieure Droite'},
    {'fdi': '84', 'univ': 'S', 'palmer': None, 'arch': 'MAN', 'quad': 'LR', 'primary': True, 'en': 'Lower Right First Primary Molar', 'fr': 'Première Molaire Primaire Inférieure Droite'},
    {'fdi': '85', 'univ': 'T', 'palmer': None, 'arch': 'MAN', 'quad': 'LR', 'primary': True, 'en': 'Lower Right Second Primary Molar', 'fr': 'Deuxième Molaire Primaire Inférieure Droite'},
]


def populate_teeth(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    for tooth_data in TOOTH_DATA:
        Tooth.objects.using(db_alias).update_or_create(
            fdi_number=tooth_data['fdi'],
            defaults={
                'universal_number': tooth_data['univ'],
                'palmer_notation': tooth_data.get('palmer'), # Use .get for optional fields
                'arch': tooth_data['arch'],
                'quadrant': tooth_data['quad'],
                'is_primary': tooth_data['primary'],
                'name_en': tooth_data['en'],
                'name_fr': tooth_data['fr'],
            }
        )

def reverse_populate_teeth(apps, schema_editor):
    # Optional: You could delete them, but often static data is left.
    # Tooth = apps.get_model('core', 'Tooth')
    # db_alias = schema_editor.connection.alias
    # fdi_numbers = [t['fdi'] for t in TOOTH_DATA]
    # Tooth.objects.using(db_alias).filter(fdi_number__in=fdi_numbers).delete()
    pass # Or use migrations.RunPython.noop


class Migration(migrations.Migration):

    dependencies = [
        ('tooth', '0002_remove_tooth_name_tooth_name_en_tooth_name_fr'),
    ]

    operations = [
        migrations.RunPython(populate_teeth, reverse_code=reverse_populate_teeth),
    ]
