# Generated by Django 5.1 on 2025-02-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_clinic_name_user_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DENTIST', 'Dentist'), ('RECEPTIONIST', 'Receptionist')], default='RECEPTIONIST', max_length=20),
        ),
    ]
